name: SonarQube

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze all services
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze all microservices
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd job-service && mvn verify sonar:sonar -Dsonar.projectKey=your_project_job -Dsonar.projectName=Job-Service -Dsonar.organization=your_org -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          cd ../company-service && mvn verify sonar:sonar -Dsonar.projectKey=your_project_company -Dsonar.projectName=Company-Service -Dsonar.organization=your_org -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          cd ../auth-service && mvn verify sonar:sonar -Dsonar.projectKey=your_project_auth -Dsonar.projectName=Auth-Service -Dsonar.organization=your_org -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          cd ../gateway-service && mvn verify sonar:sonar -Dsonar.projectKey=your_project_gateway -Dsonar.projectName=Gateway-Service -Dsonar.organization=your_org -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
